---

- name: Create Directory for api
  file:
    state: directory
    path: "{{ api_directory }}"
    owner: "{{ api_user }}"
    group: "{{ api_group }}"
  tags: ["api_setup"]

- name: Login to docker-Registry (if configured)
  docker_login:
    username: "{{ api_docker_username }}"
    password: "{{ api_docker_password }}"
    registry: "{{ api_docker_registry }}"
  when: api_docker_private|bool
  tags: ["api_deploy"]

- name: Copy Docker-compose manifest
  template:
    src: templates/docker-compose.yml.j2
    dest: "{{ api_directory }}/docker-compose.yml"
  notify: restart docker-compose for project
  tags: ["api_deploy"]

- name: Run Docker-Compose for project
  docker_compose:
    project_src: "{{ api_directory }}"
    state: present
  tags: ["api_deploy"]

- name: Logout From Docker Private registry
  docker_login:
    registry: "{{ api_docker_registry }}"
    state: absent
  when: api_docker_private|bool
  tags: ["api_deploy"]
